stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: |
        echo "Pipeline Variable: $(PipelineVariable)"
        echo "Build Number: $(Build.BuildNumber)"
        echo "Build ID: $(Build.BuildId)"
        echo "Branch: $(Build.SourceBranchName)"
        echo "Sources: $(Build.SourcesDirectory)"
        echo "Artifacts: $(Build.ArtifactStagingDirectory)"
        ls -R $(System.DefaultWorkingDirectory)
      displayName: "Display Build Variables"