
trigger:
- main
pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Start with stages
    - bash: echo$(PipelineVariable)
    - bash: echo$(Build.BuildNumber)
    - bash: echo$(Build.BuildId)
    - bash: echo$(Build.SourcebranchName)
    - bash: echo$(Build.SourceDirectory)
    - bash: ls-R $(System.DefaultWorkingDirectory)
    - bash: echo$(Build.ArtifactStagingDirectory)

